version: '3'

services:
  chatgpt:
    container_name: chatgpt
    image: registry.cn-hangzhou.aliyuncs.com/eryajf/chatgpt-wecom
    restart: always
    environment:
      LOG_LEVEL: "info" # 应用的日志级别 info/debug
      CORP_ID: "" # 企业ID
      AGENT_ID: "" # 应用ID
      AGENT_SECRET: "" # 应用秘钥
      RECEIVE_MSG_TOKEN: "" # API接收消息的token
      RECEIVE_MSG_KEY: "" # API接收消息的key
      APIKEY: xxxxxx # 你的 api_key
      BASE_URL: "" # 如果你使用官方的接口地址 https://api.openai.com，则留空即可，如果你想指定请求url的地址，可通过这个参数进行配置，注意需要带上 http 协议
      MODEL: "gpt-3.5-turbo-0613" # 指定模型，默认为 gpt-3.5-turbo , 可选参数有： "gpt-4-32k-0613", "gpt-4-32k-0314", "gpt-4-32k", "gpt-4-0613", "gpt-4-0314", "gpt-4", "gpt-3.5-turbo-16k-0613", "gpt-3.5-turbo-16k", "gpt-3.5-turbo-0613", "gpt-3.5-turbo-0301", "gpt-3.5-turbo"，如果使用gpt-4，请确认自己是否有接口调用白名单，如果你是用的是azure，则该配置项可以留空或者直接忽略
      SESSION_TIMEOUT: 600 # 会话超时时间,默认600秒,在会话时间内所有发送给机器人的信息会作为上下文
      MAX_QUESTION_LEN: 2048 # 最大问题长度，默认4096 token，正常情况默认值即可，如果使用gpt4-8k或gpt4-32k，可根据模型token上限修改。
      MAX_ANSWER_LEN: 2048 # 最大回答长度，默认4096 token，正常情况默认值即可，如果使用gpt4-8k或gpt4-32k，可根据模型token上限修改。
      MAX_TEXT: 4096 # 最大文本 = 问题 + 回答, 接口限制，默认4096 token，正常情况默认值即可，如果使用gpt4-8k或gpt4-32k，可根据模型token上限修改。
      HTTP_PROXY: http://host.docker.internal:15777 # 指定请求时使用的代理，如果为空，则不使用代理，注意需要带上 http 协议 或 socks5 协议
      DEFAULT_MODE: "单聊" # 指定默认的对话模式，可根据实际需求进行自定义，如果不设置，默认为单聊，即无上下文关联的对话模式
      MAX_REQUEST: 0 # 单人单日请求次数上限，默认为0，即不限制
      PORT: 8000 # 指定服务启动端口，默认为 8000，容器化部署时，不需要调整，一般在二进制宿主机部署时，遇到端口冲突时使用，如果run_mode为stream模式，则可以忽略该配置项
      SERVICE_URL: "" # 指定服务的地址，就是当前服务可供外网访问的地址(或者直接理解为你配置在企微回调那里的地址)
      # 以下 ALLOW_USERS、DENY_USERS、VIP_USERS、ADMIN_USERS 配置中填写的是用户的userid 比如 ["1301691029702722","1301691029702733"]，这个信息需要在企微管理后台的通讯录当中获取：https://work.weixin.qq.com/wework_admin/frame#contacts
      ALLOW_USERS: "" # 哪些用户可以进行对话，如果留空，则表示允许所有用户，如果要限制，则填写用户的userid
      DENY_USERS: "" # 哪些用户不可以进行对话，如果留空，则表示允许所有用户（如allow_user有配置，需满足相应条件），如果要限制，则列表中写用户的userid，黑名单优先级高于白名单
      VIP_USERS: "" # 哪些用户可以进行无限对话，如果留空，则表示只允许管理员（如max_request配置为0，则允许所有人），如果要针对指定VIP用户放开限制（如max_request配置不为0），则列表中写用户的userid
      ADMIN_USERS: "" # 指定哪些人为此系统的管理员，如果留空，则表示没有人是管理员，如果要限制，则列表中写用户的userid
      SENSITIVE_WORDS: "" # 敏感词，提问时触发，则不允许提问，回答的内容中触发，则以 🚫 代替
      AZURE_ON: "false" # 是否走Azure OpenAi API, 默认false ,如果为true，则需要配置下边的四个参数
      AZURE_API_VERSION: "" # Azure OpenAi API 版本，比如 "2023-03-15-preview"
      AZURE_RESOURCE_NAME: "" # Azure OpenAi API 资源名称，比如 "openai"
      AZURE_DEPLOYMENT_NAME: "" # Azure OpenAi API 部署名称，比如 "openai"
      AZURE_OPENAI_TOKEN: "" # Azure token
      HELP: "Commands:


        =================================


        🙋 单聊 👉 单独聊天，缺省


        🗣 串聊 👉 带上下文聊天


        🔃 重置 👉 重置带上下文聊天


        🚀 帮助 👉 显示帮助信息


        =================================


        💪 Power By [eryajf/chatgpt-wecom](https://github.com/eryajf/chatgpt-wecom)" # 帮助信息，放在配置文件，可供自定义
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    extra_hosts:
      - host.docker.internal:host-gateway
