on: push
name: Automatic Generation TOC
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: "**目录**"
          MAX_HEADER_LEVEL: 4